need to specify sass-rails version >4.0.0
was getting NoMethodError: undefined method `environment'
for nil:NilClass when compiling assets on heroku. found
solution at see http://stackoverflow.com/a/22395250/303896